### PR TITLE
Details post of category creation added

### PR DESCRIPTION
**Pull request by HabibRh26**
Hello, As I saw lots of people are interested to know about how to create blog post and category in this theme that's why I just put up an effort to show them a guideline. Please review the request.

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @HabibRh26 for very detailed post. I will have full review soon. It may take few days. Till then, anyone can find your post here: [Creating Category](https://deploy-preview-7--toha.netlify.app/posts/writing-posts/category/creating-category/)

**Review by HabibRh26 — COMMENTED** [review]
little correction added

**Comment by hossainemruz** [comment]
@HabibRh26 I have updated the customizing post author's section. I have also added you as the author of this post.

**Comment by hossainemruz** [comment]
Post: https://toha.netlify.app/posts/writing-posts/category/creating-category/

**Pull request merged**
